name: New APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: آزاد کردن فضای دیسک
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true

      - name: دریافت کدها از مخزن
        uses: actions/checkout@v4

      - name: ساخت خروجی اندروید با یونیتی
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: Android
          unityVersion: 2021.3.30f1

      - name: آپلود فایل APK ساخته شده
        uses: actions/upload-artifact@v4
        with:
          name: خروجی-اندروید
          path: build/Android
